### ISSUE TITLE
Hard-code 0s in the matrix

### ISSUE THREAD

**Issue by gherardovarando** [gherardovarando/gmat-js#1]
https://github.com/irenecrsn/gmat/issues/18

**Comment by gherardovarando** [comment]
Done, and also we hard code the 1 in the diagonal.

**Comment by irenecrsn** [comment]
Maybe because of this the eigenvalue densities are different?

**Comment by irenecrsn** [comment]
OK, but if the results change so much when rounding, then the numeric errors propagated through the algorithm have much more impact than they should. Maybe we should keep this in mind, and compare with what we obtain when orthogonalizing differently.

If for example we are going to do experiments to see the properties of the distribution, these could be importantly biased by those numeric errors (such as how ill conditioned the matrices are).
